/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dikeuscBridgeSol from "./DIKEUSCBridge.sol";
export type { dikeuscBridgeSol };
export type { DIKERegistry } from "./DIKERegistry";
export type { IDIKERegistry } from "./IDIKERegistry";
