/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DIKEUSCBridge {
  export type RepaymentProofStruct = {
    borrower: AddressLike;
    amount: BigNumberish;
    sourceChainId: BigNumberish;
    sourceTxHash: BytesLike;
    sourceProtocol: AddressLike;
    timestamp: BigNumberish;
  };

  export type RepaymentProofStructOutput = [
    borrower: string,
    amount: bigint,
    sourceChainId: bigint,
    sourceTxHash: string,
    sourceProtocol: string,
    timestamp: bigint
  ] & {
    borrower: string;
    amount: bigint;
    sourceChainId: bigint;
    sourceTxHash: string;
    sourceProtocol: string;
    timestamp: bigint;
  };
}

export interface DIKEUSCBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dikeRegistry"
      | "owner"
      | "pause"
      | "paused"
      | "processedProofs"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "verifyAndRecordBorrow"
      | "verifyAndRecordRepayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BorrowVerified"
      | "OwnershipTransferred"
      | "Paused"
      | "RepaymentVerified"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dikeRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedProofs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAndRecordBorrow",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndRecordRepayment",
    values: [DIKEUSCBridge.RepaymentProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "dikeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndRecordBorrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndRecordRepayment",
    data: BytesLike
  ): Result;
}

export namespace BorrowVerifiedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amount: BigNumberish,
    sourceChainId: BigNumberish,
    sourceTxHash: BytesLike
  ];
  export type OutputTuple = [
    borrower: string,
    amount: bigint,
    sourceChainId: bigint,
    sourceTxHash: string
  ];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
    sourceChainId: bigint;
    sourceTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentVerifiedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amount: BigNumberish,
    sourceChainId: BigNumberish,
    sourceTxHash: BytesLike
  ];
  export type OutputTuple = [
    borrower: string,
    amount: bigint,
    sourceChainId: bigint,
    sourceTxHash: string
  ];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
    sourceChainId: bigint;
    sourceTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIKEUSCBridge extends BaseContract {
  connect(runner?: ContractRunner | null): DIKEUSCBridge;
  waitForDeployment(): Promise<this>;

  interface: DIKEUSCBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dikeRegistry: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processedProofs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyAndRecordBorrow: TypedContractMethod<
    [
      borrower: AddressLike,
      amount: BigNumberish,
      sourceChainId: BigNumberish,
      sourceTxHash: BytesLike,
      sourceProtocol: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  verifyAndRecordRepayment: TypedContractMethod<
    [proof: DIKEUSCBridge.RepaymentProofStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dikeRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processedProofs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyAndRecordBorrow"
  ): TypedContractMethod<
    [
      borrower: AddressLike,
      amount: BigNumberish,
      sourceChainId: BigNumberish,
      sourceTxHash: BytesLike,
      sourceProtocol: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAndRecordRepayment"
  ): TypedContractMethod<
    [proof: DIKEUSCBridge.RepaymentProofStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BorrowVerified"
  ): TypedContractEvent<
    BorrowVerifiedEvent.InputTuple,
    BorrowVerifiedEvent.OutputTuple,
    BorrowVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentVerified"
  ): TypedContractEvent<
    RepaymentVerifiedEvent.InputTuple,
    RepaymentVerifiedEvent.OutputTuple,
    RepaymentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BorrowVerified(address,uint256,uint256,bytes32)": TypedContractEvent<
      BorrowVerifiedEvent.InputTuple,
      BorrowVerifiedEvent.OutputTuple,
      BorrowVerifiedEvent.OutputObject
    >;
    BorrowVerified: TypedContractEvent<
      BorrowVerifiedEvent.InputTuple,
      BorrowVerifiedEvent.OutputTuple,
      BorrowVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RepaymentVerified(address,uint256,uint256,bytes32)": TypedContractEvent<
      RepaymentVerifiedEvent.InputTuple,
      RepaymentVerifiedEvent.OutputTuple,
      RepaymentVerifiedEvent.OutputObject
    >;
    RepaymentVerified: TypedContractEvent<
      RepaymentVerifiedEvent.InputTuple,
      RepaymentVerifiedEvent.OutputTuple,
      RepaymentVerifiedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
