/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDIKERegistry {
  export type CreditEventStruct = {
    subject: AddressLike;
    amount: BigNumberish;
    eventType: BigNumberish;
    timestamp: BigNumberish;
    referenceHash: BytesLike;
  };

  export type CreditEventStructOutput = [
    subject: string,
    amount: bigint,
    eventType: bigint,
    timestamp: bigint,
    referenceHash: string
  ] & {
    subject: string;
    amount: bigint;
    eventType: bigint;
    timestamp: bigint;
    referenceHash: string;
  };
}

export interface IDIKERegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCreditEvent"
      | "getCreditSummary"
      | "getOutstandingDebt"
      | "getUserEvents"
      | "recordEvent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCreditEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditSummary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstandingDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEvents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordEvent",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCreditEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutstandingDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordEvent",
    data: BytesLike
  ): Result;
}

export interface IDIKERegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IDIKERegistry;
  waitForDeployment(): Promise<this>;

  interface: IDIKERegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCreditEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [IDIKERegistry.CreditEventStructOutput],
    "view"
  >;

  getCreditSummary: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalBorrowed: bigint;
        totalRepaid: bigint;
        defaults: bigint;
        onTimeRepayments: bigint;
        lateRepayments: bigint;
        totalEvents: bigint;
        onTimeRatio: bigint;
        defaultRate: bigint;
      }
    ],
    "view"
  >;

  getOutstandingDebt: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserEvents: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  recordEvent: TypedContractMethod<
    [
      subject: AddressLike,
      amount: BigNumberish,
      eventType: BigNumberish,
      referenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCreditEvent"
  ): TypedContractMethod<
    [eventId: BigNumberish],
    [IDIKERegistry.CreditEventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreditSummary"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalBorrowed: bigint;
        totalRepaid: bigint;
        defaults: bigint;
        onTimeRepayments: bigint;
        lateRepayments: bigint;
        totalEvents: bigint;
        onTimeRatio: bigint;
        defaultRate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutstandingDebt"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserEvents"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "recordEvent"
  ): TypedContractMethod<
    [
      subject: AddressLike,
      amount: BigNumberish,
      eventType: BigNumberish,
      referenceHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
