/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDIKERegistry,
  IDIKERegistryInterface,
} from "../../../contracts/DIKEUSCBridge.sol/IDIKERegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
    ],
    name: "getCreditEvent",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "subject",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "eventType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "referenceHash",
            type: "bytes32",
          },
        ],
        internalType: "struct IDIKERegistry.CreditEvent",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getCreditSummary",
    outputs: [
      {
        internalType: "uint256",
        name: "totalBorrowed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalRepaid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "defaults",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "onTimeRepayments",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lateRepayments",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalEvents",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "onTimeRatio",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "defaultRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getOutstandingDebt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserEvents",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "eventType",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "referenceHash",
        type: "bytes32",
      },
    ],
    name: "recordEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDIKERegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDIKERegistryInterface {
    return new Interface(_abi) as IDIKERegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDIKERegistry {
    return new Contract(address, _abi, runner) as unknown as IDIKERegistry;
  }
}
