/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIKEUSCBridge__factory } from "./DIKEUSCBridge__factory";
export { IDIKERegistry__factory } from "./IDIKERegistry__factory";
