/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDIKERegistry,
  IDIKERegistryInterface,
} from "../../contracts/IDIKERegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "enum IDIKERegistry.EventType",
        name: "eventType",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "referenceHash",
        type: "bytes32",
      },
    ],
    name: "recordEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDIKERegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDIKERegistryInterface {
    return new Interface(_abi) as IDIKERegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDIKERegistry {
    return new Contract(address, _abi, runner) as unknown as IDIKERegistry;
  }
}
